### ISSUE TITLE
urgent help

### ISSUE THREAD

**Issue by samexclusive** [gripsack/android#68]
Mam i am final year student and i want to understand the context view of that project can you help me ??

**Comment by tugcekeser** [comment]
Definitely, we want to help you! Please watch the demo first ( https://www.youtube.com/watch?v=n_20aWs4MTE). You will get some idea about the flow and context of the project after you watched the video.  Our app is basically a travel assistance app for planning and sharing trips with our friends.  The main operations on the app are that displaying favorite places for traveling, choosing a travel destination and planning a trip, sharing trips with the user's friends, displaying the user's previous and upcoming trips, adding places to the user's bucket list to remember later. We are using Firebase to authenticate the user and save the user data. We are also using Google APIs to find the close locations to the user's travel destination. Please let us know if you need anything else.

**Comment by samexclusive** [comment]
Thanks a lot ma'am. This will help me a lot. 👍

**Comment by rdadwal10** [comment]
hello mam , i just want to know-1.Requirements Analysis
2.Scope and objective 
3.Implementation
4.Limitation and future scope
of your project.

**Comment by tugcekeser** [comment]
Hi, 
We don't have detailed documentation for this project. But, maybe following notes can be helpful for you.
1-) Requirement Analysis - You can find "Functional Requirements" in the user stories part in Readme.md file. For "Non-functional Requirements", you need to review the code.
2-) Scope and objective - Please review the Readme.md file again.
3-) Implementation -  If you read my answer above and Readme.md file, you will have an idea about the implementation.
4-) Limitation and future scope -  Future scope could be increasing the speed and decreasing the memory usage. For example, We can improve the network call method and use Retrofit or Volley libraries according to our needs.

Overall, my kindly suggestion is that you should do your school project by yourself and learn the concepts better. These concepts are the basic concepts of Software Engineering and you will do all these every time while you're working. Please let us know if you need anything else.
