### ISSUE TITLE
[ExploreFragment] not display recommended places

### ISSUE THREAD

**Issue by soozuang** [gripsack/android#69]
I cloned project to Android Studio and build it already, but nothings display on my Explore view.
Please help

**Comment by soozuang** [comment]
And the searchbar said that "Can't load search result" for "San Francisco" input

**Comment by soozuang** [comment]
Can you give me your JSON format sample pls

**Comment by tugcekeser** [comment]
Hi @soozuang ,
To get the search results, you need to use your own Google API key. In addition, for running the remaining parts of application, you also need to create a Firebase project and bind it to this projects. We did not put our own keys  in the project.

**Comment by eviltweats** [comment]
Did you get solution to this problem?? i am having same issues .
