### ISSUE TITLE
I cant see any Explore Recommended places in this app .

### ISSUE THREAD

**Issue by eviltweats** [gripsack/android#70]
I dont know if i am missing or something. PLese help.

**Comment by eviltweats** [comment]
Nevermind.. i got it. It was my noob mistake. Btw how do you guys handling your google api usage quota?? are you guys paying extra money for it or not?? Just wondering

**Comment by tugcekeser** [comment]
This was the just for our bootcamp project. Therefore, we did not pay money for api usage quota.
